name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build project
        run: ./gradlew build

  test:
    name: Run unit tests with coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run unit tests
        run: ./gradlew test

      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v1
        with:
          name: Jacoco Report
          path: build/reports/jacoco/test